### ISSUE TITLE
TweetParam test is failing by returning null not full URL

### ISSUE THREAD

**Issue by startupsandcode** [ember-learn/super-rentals-tutorial#180] opened 2021-03-16 18:34 UTC
Page with issue:
https://guides.emberjs.com/release/tutorial/part-2/service-injection/

Assert that is failing:
```
assert.equal(
      this.tweetParam('url'),
      new URL('/foo/bar?baz=true#some-section', window.location.origin)
    );
```

![image](https://user-images.githubusercontent.com/939730/111361737-68522e80-8664-11eb-886c-41cd911338f5.png)

It appears it is comparing at string to a url, and the following is not returning a URL

class MockRouterService extends Service {
  get currentURL() {
    return '/foo/bar?baz=true#some-section';
  }

**Comment by ijlee2** [comment] 2021-03-20 06:25
@startupsandcode Hello. I followed the tutorial up to the end of [Service Injection](https://guides.emberjs.com/release/tutorial/part-2/service-injection/) and wasn't able to reproduce the issue.

It seemed like the issue is unrelated to #179 (i.e. the `basic usage` test passed in both `ember-source v3.25.1` and `v3.25.3`). If you have your tutorial app on GitHub, I think that'd help us with debugging.

For reference, you can check out https://github.com/ijlee2/super-rentals-tutorial-3.25/commit/fadad631aea38679ea5d803eb2f7f5501c33d74b.

**Comment by startupsandcode** [comment] 2021-03-21 00:02
I was able to reproduce it.  I am wondering if it has something to do with windows vs macos.  I'm on windows.
Here is the repo I am using for this:
https://github.com/startupsandcode/ember-tuts

**Comment by ijlee2** [comment] 2021-03-21 13:59
Thanks for posting your repo app. It helped a lot. (The video recording was great too!)


### 1. What happened

In your test, the line `this.owner.register('service:router', MockRouterService);` didn't work. In other words, Ember didn't end up stubbing the `router` service. I was able to check this by adding the line,

```javascript
const routerService = this.owner.lookup('service:router');
debugger;
```

in the test, then checking the value of `routerService` in Chrome console while the test is running.

As a result, in the assertion,

```javascript
assert.equal(
  this.tweetParam('url'),
  new URL('/foo/bar?baz=true#some-section', window.location.origin)
);
```

the actual value `this.tweetParam('url')` was evaluated to the string `'http://localhost:7357/null'` instead of `'http://localhost:7357/foo/bar?baz=true#some-section'`.

As an aside, I think the assertion is a bit magical. The expected value `new URL(...)` returns a URL object, so I wouldn't have expected `assert.equal(...)` to work. I imagine that there's something behind the scenes (maybe calling `.toString()`) that allows comparing a string to a URL object.

A better assertion may be,

```javascript
assert.strictEqual(
  this.tweetParam('url'),
  new URL('/foo/bar?baz=true#some-section', window.location.origin).href
);
```


### 2. Why it happened

This one is still a mystery to me. The problem was caused by installing `ember-component-css`. You will find that, if you run `yarn remove ember-component-css`, then all tests will pass.

I imagine there's some dependent package of `ember-component-css` that didn't allow stubbing the `router` service, but I didn't have time to investigate further.

Since the Super Rentals tutorial app is a simple one, you can also uninstall `ember-cli-sass` and `sass`, then rename the file `app/styles/app.scss` to `app/styles/app.css`.

If, in a production app, you want to localize stylesheets, I would suggest looking at `ember-css-modules` and not installing `sass`. (I feel like `sass` isn't as needed once you have style definitions that are local.)


### 3. What now?

If you happen to find out what exactly in `ember-component-css` caused the assertion to fail, I would suggest opening an issue in the `ember-component-css` repo in case the maintainers may want to release a patch.

I noticed that your Mapbox key has been committed, so I also recommend deleting the GitHub repo or hiding the key by updating the commit history.


Hope this helps!

**Comment by startupsandcode** [comment] 2021-03-22 14:47
Thanks, confirmed that
```
yarn remove ember-component-css
```
does solve the problem.  I'll check into the dependencies of that library and see what happens, but for now, it solved it and should be good.  Thanks for the mapbox note, I'll delete the repo now, was using it for testing only.

**Comment by ijlee2** [comment] 2021-03-23 06:14
@startupsandcode Awesome, thanks!

**Closed by ijlee2** 2021-03-23 06:14 UTC
